name: workflow_product

on:
  schedule:
    - cron: "*/2 * * * *"  
  workflow_dispatch:      

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update json/product_api.json
        run: |
          echo '[
                {"product_ID":1,"product":"Wireless Headphones","sk u":"WH-1001","category":"electronics","sub_category":"Audio","brand":"Sony","model_year":2023},
                {"product_ID":2,"product":"Smartphone","sk u":"SP-2002","category":"Electronics","sub_category":"Mobile","brand":"Samsung","model_year":2024},
                {"product_ID":3,"product":"Laptop","sk u":"LP-3003","category":"Computers","sub_category":"Notebooks","brand":"Dell","model_year":2023 },
                {"product_ID":4,"product":"Smartwatch","sk u":"SW-4004","category":"Electronics","sub_category":"Wearables","brand":"Apple","model_year": 2025},
                {"product_ID":5,"product":"Bluetooth Speaker","sk u":"BS-5005","category":"Electronics","sub_category":"Audio","brand":"JBL","model_year":2022},
                {"product_ID":6,"product":"Tablet","sk u":"TB-6006","category":"Electronics","sub_category":"Mobile","brand":"Lenovo","model_year": 2024},
                {"product_ID":7,"product":"Desktop Monitor","sk u":"DM-7007","category":"computers","sub_category":"Displays","brand":"LG","model_year": 2023},
                {"product_ID":8,"product":"Mechanical Keyboard","sk u":"MK-8008","category":"Computers","sub_category":"Accessories","brand":"Logitech","model_year": 2023},
                {"product_ID":9,"product":"Gaming Mouse","sk u":"GM-9009","category":"computers","sub_category":"Accessories","brand":"Razer","model_year":2024 },
                {"product_ID":10,"product":"Webcam","sk u":"WC-1010","category":"Electronics","sub_category":"Video","brand":"Microsoft","model_year":2022},
                {"product_ID":11,"product":"Portable SSD","sk u":"PS-1111","category":"Storage","sub_category":"External Drives","brand":"SanDisk","model_year":2024},
                {"product_ID":12,"product":"USB Flash Drive","sk u":"UF-1212","category":"storage","sub_category":"External Drives","brand":"Kingston","model_year":2023},
                {"product_ID":13,"product":"Wireless Charger","sk u":"WC-1313","category":"Electronics","sub_category":"Chargers","brand":"Anker","model_year":2024},
                {"product_ID":14,"product":"Noise Cancelling Earbuds","sk u":"NE-1414","category":"Electronics","sub_category":"Audio","brand":"Bose","model_year":2025},
                {"product_ID":15,"product":"Smart TV","sk u":"ST-1515","category":"Electronics","sub_category":"Video","brand":"Philips","model_year":2023},
                {"product_ID":16,"product":"Router","sk u":"RT-1616","category":"networking","sub_category":"WiFi","brand":"TP-Link","model_year":2023},
                {"product_ID":17,"product":"Power Bank","sk u":"PB-1717","category":"Electronics","sub_category":"Chargers","brand":"Xiaomi","model_year":2024 },
                {"product_ID":18,"product":"Drone","sk u":"DR-1818","category":"Electronics","sub_category":"Cameras","brand":"DJI","model_year":2024},
                {"product_ID":19,"product":"Action Camera","sk u":"AC-1919","category":"cameras","sub_category":"Video","brand":"GoPro","model_year":2023},
                {"product_ID":20,"product":"VR Headset","sk u":"VR-2020","category":"Electronics","sub_category":"Gaming","brand":"Meta","model_year":2025},
                {"product_ID":21,"product":"Smart Home Hub","sk u":"SH-2121","category":"home","sub_category":"Automation","brand":"Amazon","model_year": 2023},
                {"product_ID":22,"product":"3D Printer","sk u":"PR-2222","category":"electronics","sub_category":"Printing","brand":"Creality","model_year":2024 },
                {"product_ID":23,"product":"External Hard Drive","sk u":"EH-2323","category":"Storage","sub_category":"External Drives","brand":"Western Digital","model_year":2023},
                {"product_ID":24,"product":"Smart Thermostat","sk u":"ST-2424","category":"Home","sub_category":"Automation","brand":"Tado","model_year":2025  },
                {"product_ID":25,"product":"Robot Vacuum","sk u":"RV-2525","category":"Home","sub_category":"Appliances","brand":"iRobot","model_year":2024},
                {"product_ID":26,"product":"Wireless Microphone","sk u":"WM-2626","category":"Audio","sub_category":"Recording","brand":"Shure","model_year":2023},
                {"product_ID":27,"product":"Graphic Tablet","sk u":"GT-2727","category":"Computers","sub_category":"Accessories","brand":"Wacom","model_year": 2024},
                {"product_ID":28,"product":"Electric Scooter","sk u":"ES-2828","category":"Transport","sub_category":"Urban Mobility","brand":"Segway","model_year":2024},
                {"product_ID":29,"product":"Dash Camera","sk u":"DC-2929","category":"Cameras","sub_category":"Automotive","brand":"Nextbase","model_year":2023},
                {"product_ID":29,"product":"Dash Camera","sk u":"DC-2929","category":"Cameras","sub_category":"Automotive","brand":"Nextbase","model_year":2023},
                {"product_ID":30,"product":"LED Desk Lamp","sk u":"LD-3030","category":"home","sub_category":"Lighting","brand":"Philips","model_year":2022}
              ]' > json/product_api.json

      - name: Commit and push changes
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add json/product_api.json
            git commit -m "Auto-update JSON [$(date)]" || echo "No changes to commit"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
